CREATE SCHEMA IF NOT EXISTS __SCHEMA__;
CREATE TABLE IF NOT EXISTS __SCHEMA__.schema_migrations(version text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
INSERT INTO __SCHEMA__.schema_migrations(version) VALUES ('001_init') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS __SCHEMA__.accounts(
 account_id text PRIMARY KEY, environment text NOT NULL DEFAULT 'PAPER' CHECK(environment='PAPER'), currency text NOT NULL DEFAULT 'INR', opening_cash numeric(24,8) NOT NULL CHECK(opening_cash>=0), available_cash numeric(24,8) NOT NULL CHECK(available_cash>=0), reserved_capital numeric(24,8) NOT NULL DEFAULT 0 CHECK(reserved_capital>=0), status text NOT NULL DEFAULT 'ACTIVE', risk_limits jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), version bigint NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS __SCHEMA__.strategy_registry(strategy_id text PRIMARY KEY, strategy_name text NOT NULL, family text, enabled boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS __SCHEMA__.strategy_versions(strategy_id text NOT NULL REFERENCES __SCHEMA__.strategy_registry, version text NOT NULL, config jsonb NOT NULL DEFAULT '{}', immutable_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(strategy_id,version));
CREATE TABLE IF NOT EXISTS __SCHEMA__.instrument_snapshots(instrument_snapshot_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), instrument_id text NOT NULL, instrument_token text, exchange text NOT NULL, segment text NOT NULL, symbol text NOT NULL, underlying text, expiry date, strike numeric(24,8), option_type text, lot_size numeric(24,8) NOT NULL CHECK(lot_size>0), multiplier numeric(24,8) NOT NULL CHECK(multiplier>0), master_version text, snapshot jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS instrument_snapshots_token_idx ON __SCHEMA__.instrument_snapshots(exchange,instrument_token,created_at DESC);
CREATE TABLE IF NOT EXISTS __SCHEMA__.cost_profiles(cost_profile_id text NOT NULL, version integer NOT NULL, asset_class text NOT NULL, exchange text NOT NULL, segment text NOT NULL, effective_from date NOT NULL, effective_to date, enabled boolean NOT NULL DEFAULT false, rates jsonb NOT NULL, source_url text, verified_at timestamptz, PRIMARY KEY(cost_profile_id,version));
CREATE TABLE IF NOT EXISTS __SCHEMA__.tax_profiles(tax_profile_id text PRIMARY KEY, scope text NOT NULL, positive_profit_rate numeric(12,8) NOT NULL CHECK(positive_profit_rate BETWEEN 0 AND 1), loss_offsets boolean NOT NULL DEFAULT false, description text NOT NULL);
CREATE TABLE IF NOT EXISTS __SCHEMA__.webhook_subscriptions(subscription_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), endpoint_url text NOT NULL, event_types text[] NOT NULL DEFAULT '{}', enabled boolean NOT NULL DEFAULT true, is_critical boolean NOT NULL DEFAULT false, auth_kind text NOT NULL DEFAULT 'BASIC', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS __SCHEMA__.trading_sessions(exchange text NOT NULL, session_date date NOT NULL, opens_at timestamptz, closes_at timestamptz, square_off_at timestamptz, is_holiday boolean NOT NULL DEFAULT false, is_special boolean NOT NULL DEFAULT false, source text NOT NULL, calendar_version text NOT NULL, PRIMARY KEY(exchange,session_date));
CREATE TABLE IF NOT EXISTS __SCHEMA__.system_configuration_versions(config_version uuid PRIMARY KEY DEFAULT gen_random_uuid(), config_hash text NOT NULL UNIQUE, configuration jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS __SCHEMA__.trade_intents(
 trade_intent_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), client_event_id text NOT NULL, account_id text NOT NULL REFERENCES __SCHEMA__.accounts, source_service text NOT NULL, idempotency_key text NOT NULL, request_hash text NOT NULL, strategy_id text NOT NULL, strategy_version text NOT NULL, signal_id text NOT NULL, environment text NOT NULL CHECK(environment='PAPER'), status text NOT NULL CHECK(status IN ('RECEIVED','VALIDATED','ACCEPTED','REJECTED','FAILED')), rejection_reason text, request_json jsonb NOT NULL, correlation_id uuid NOT NULL, received_at timestamptz NOT NULL DEFAULT now(), UNIQUE(source_service,idempotency_key), UNIQUE(strategy_id,strategy_version,signal_id));
CREATE INDEX IF NOT EXISTS trade_intents_account_status_idx ON __SCHEMA__.trade_intents(account_id,status,received_at DESC);
CREATE TABLE IF NOT EXISTS __SCHEMA__.idempotency_records(source_service text NOT NULL, idempotency_key text NOT NULL, request_hash text NOT NULL, resource_type text NOT NULL, resource_id uuid NOT NULL, response_code int NOT NULL, response_json jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(source_service,idempotency_key));
CREATE TABLE IF NOT EXISTS __SCHEMA__.request_audit(request_audit_id bigserial PRIMARY KEY, occurred_at timestamptz NOT NULL DEFAULT now(), source_service text, correlation_id uuid, authentication_result text NOT NULL, operation text NOT NULL, result text NOT NULL, detail jsonb NOT NULL DEFAULT '{}');

CREATE TABLE IF NOT EXISTS __SCHEMA__.trade_groups(
 trade_group_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), trade_intent_id uuid REFERENCES __SCHEMA__.trade_intents, account_id text NOT NULL REFERENCES __SCHEMA__.accounts, client_group_id text NOT NULL, strategy_id text NOT NULL, strategy_version text NOT NULL, asset_class text NOT NULL, expected_leg_count int NOT NULL CHECK(expected_leg_count>0), entry_policy text NOT NULL, close_policy text NOT NULL, performance_basis_type text NOT NULL, performance_basis_amount numeric(24,8), status text NOT NULL, fully_closed boolean NOT NULL DEFAULT false, opened_at timestamptz, closed_at timestamptz, event_sequence bigint NOT NULL DEFAULT 0, metadata jsonb NOT NULL DEFAULT '{}', version bigint NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(account_id,client_group_id));
CREATE INDEX IF NOT EXISTS trade_groups_open_idx ON __SCHEMA__.trade_groups(account_id,status,created_at DESC);
CREATE TABLE IF NOT EXISTS __SCHEMA__.trade_legs(
 trade_leg_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), trade_group_id uuid NOT NULL REFERENCES __SCHEMA__.trade_groups ON DELETE RESTRICT, client_leg_id text NOT NULL, instrument_snapshot_id uuid NOT NULL REFERENCES __SCHEMA__.instrument_snapshots, role text NOT NULL, side text NOT NULL CHECK(side IN ('BUY','SELL')), quantity_unit text NOT NULL, requested_quantity numeric(24,8) NOT NULL CHECK(requested_quantity>0), total_units numeric(24,8) NOT NULL CHECK(total_units>0), filled_quantity numeric(24,8) NOT NULL DEFAULT 0 CHECK(filled_quantity>=0), remaining_quantity numeric(24,8) NOT NULL CHECK(remaining_quantity>=0), average_entry_price numeric(24,8), average_exit_price numeric(24,8), status text NOT NULL, opened_at timestamptz, closed_at timestamptz, version bigint NOT NULL DEFAULT 1, UNIQUE(trade_group_id,client_leg_id), CHECK(filled_quantity<=requested_quantity));
CREATE INDEX IF NOT EXISTS trade_legs_open_idx ON __SCHEMA__.trade_legs(status,trade_group_id);
CREATE TABLE IF NOT EXISTS __SCHEMA__.paper_orders(
 paper_order_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), trade_group_id uuid NOT NULL REFERENCES __SCHEMA__.trade_groups, trade_leg_id uuid NOT NULL REFERENCES __SCHEMA__.trade_legs, position_effect text NOT NULL, side text NOT NULL, order_type text NOT NULL, time_in_force text NOT NULL, price_source text NOT NULL, limit_price numeric(24,8), stop_price numeric(24,8), requested_quantity numeric(24,8) NOT NULL CHECK(requested_quantity>0), filled_quantity numeric(24,8) NOT NULL DEFAULT 0 CHECK(filled_quantity>=0), status text NOT NULL, accepted_at timestamptz NOT NULL, expires_at timestamptz, source_request_id uuid, version bigint NOT NULL DEFAULT 1, CHECK(filled_quantity<=requested_quantity));
CREATE INDEX IF NOT EXISTS paper_orders_pending_idx ON __SCHEMA__.paper_orders(status,accepted_at);
CREATE TABLE IF NOT EXISTS __SCHEMA__.paper_fills(paper_fill_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), paper_order_id uuid NOT NULL REFERENCES __SCHEMA__.paper_orders, trade_leg_id uuid NOT NULL REFERENCES __SCHEMA__.trade_legs, source_bar_id text NOT NULL, filled_at timestamptz NOT NULL, quantity numeric(24,8) NOT NULL CHECK(quantity>0), price numeric(24,8) NOT NULL CHECK(price>0), spread_cost numeric(24,8) NOT NULL DEFAULT 0, slippage_cost numeric(24,8) NOT NULL DEFAULT 0, fill_model_version text NOT NULL, UNIQUE(paper_order_id,source_bar_id));
CREATE TABLE IF NOT EXISTS __SCHEMA__.positions(position_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), trade_leg_id uuid NOT NULL UNIQUE REFERENCES __SCHEMA__.trade_legs, opened_quantity numeric(24,8) NOT NULL DEFAULT 0, closed_quantity numeric(24,8) NOT NULL DEFAULT 0, remaining_quantity numeric(24,8) NOT NULL DEFAULT 0, average_entry_price numeric(24,8), average_exit_price numeric(24,8), realised_pnl numeric(24,8) NOT NULL DEFAULT 0, unrealised_pnl numeric(24,8) NOT NULL DEFAULT 0, last_mark numeric(24,8), last_mark_at timestamptz, version bigint NOT NULL DEFAULT 1, CHECK(closed_quantity<=opened_quantity), CHECK(remaining_quantity=opened_quantity-closed_quantity));
CREATE TABLE IF NOT EXISTS __SCHEMA__.position_lots(position_lot_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), position_id uuid NOT NULL REFERENCES __SCHEMA__.positions, opening_fill_id uuid NOT NULL REFERENCES __SCHEMA__.paper_fills, opened_quantity numeric(24,8) NOT NULL, remaining_quantity numeric(24,8) NOT NULL, entry_price numeric(24,8) NOT NULL, UNIQUE(opening_fill_id));
CREATE TABLE IF NOT EXISTS __SCHEMA__.close_intents(close_intent_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), trade_group_id uuid NOT NULL REFERENCES __SCHEMA__.trade_groups, client_event_id text NOT NULL, idempotency_key text NOT NULL, request_hash text NOT NULL, scope text NOT NULL, reason text NOT NULL, price_policy text NOT NULL, request_json jsonb NOT NULL, status text NOT NULL, received_at timestamptz NOT NULL DEFAULT now(), UNIQUE(trade_group_id,idempotency_key));
CREATE TABLE IF NOT EXISTS __SCHEMA__.execution_exit_rules(exit_rule_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), trade_group_id uuid NOT NULL REFERENCES __SCHEMA__.trade_groups, client_rule_id text NOT NULL, kind text NOT NULL, value numeric(24,8) NOT NULL, action text NOT NULL, quantity_pct numeric(12,8), active boolean NOT NULL DEFAULT true, UNIQUE(trade_group_id,client_rule_id));

CREATE TABLE IF NOT EXISTS __SCHEMA__.target_definitions(target_definition_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), trade_group_id uuid NOT NULL REFERENCES __SCHEMA__.trade_groups, target_code text NOT NULL, lifecycle text NOT NULL CHECK(lifecycle IN ('INTRADAY','SWING')), target_pct numeric(12,8) NOT NULL CHECK(target_pct>0), execution_action text NOT NULL DEFAULT 'TRACK_ONLY', UNIQUE(trade_group_id,target_code));
CREATE TABLE IF NOT EXISTS __SCHEMA__.target_tracks(target_track_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), target_definition_id uuid NOT NULL REFERENCES __SCHEMA__.target_definitions, trade_leg_id uuid NOT NULL REFERENCES __SCHEMA__.trade_legs, status text NOT NULL, entry_price numeric(24,8), target_price numeric(24,8), activated_at timestamptz, first_hit_at timestamptz, elapsed_bars bigint, elapsed_minutes bigint, mfe_before_target numeric(18,10), mae_before_target numeric(18,10), result_kind text NOT NULL DEFAULT 'HYPOTHETICAL', version bigint NOT NULL DEFAULT 1, UNIQUE(target_definition_id,trade_leg_id));
CREATE INDEX IF NOT EXISTS target_tracks_active_idx ON __SCHEMA__.target_tracks(status,trade_leg_id);
CREATE TABLE IF NOT EXISTS __SCHEMA__.target_hits(target_hit_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), target_track_id uuid NOT NULL UNIQUE REFERENCES __SCHEMA__.target_tracks, source_bar_id text NOT NULL, hit_at timestamptz NOT NULL, source_price numeric(24,8) NOT NULL, assumed_exit_price numeric(24,8) NOT NULL, gross_pnl numeric(24,8) NOT NULL, estimated_costs numeric(24,8) NOT NULL, tax_provision numeric(24,8) NOT NULL, after_tax_pnl numeric(24,8) NOT NULL, sequence_ambiguous boolean NOT NULL DEFAULT false, calculation_version text NOT NULL);
CREATE TABLE IF NOT EXISTS __SCHEMA__.observation_trackers(observation_tracker_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), trade_leg_id uuid NOT NULL UNIQUE REFERENCES __SCHEMA__.trade_legs, status text NOT NULL, entry_session date, last_session_date date, sessions_observed int NOT NULL DEFAULT 0, bars_observed bigint NOT NULL DEFAULT 0, time_below_entry_minutes bigint NOT NULL DEFAULT 0, highest_price numeric(24,8), lowest_price numeric(24,8), mfe numeric(18,10), mae numeric(18,10), peak_to_trough_drawdown numeric(18,10), recovery_at timestamptz, completed_at timestamptz, censor_reason text, version bigint NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS __SCHEMA__.horizon_outcomes(horizon_outcome_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), observation_tracker_id uuid NOT NULL REFERENCES __SCHEMA__.observation_trackers, horizon_sessions int NOT NULL CHECK(horizon_sessions IN (1,5,30)), status text NOT NULL, completed_at timestamptz, max_high_return numeric(18,10), max_close_return numeric(18,10), mae numeric(18,10), closing_return numeric(18,10), sessions_below_entry int, max_consecutive_below int, peak_to_trough_drawdown numeric(18,10), after_cost_pnl numeric(24,8), after_tax_pnl numeric(24,8), detail jsonb NOT NULL DEFAULT '{}', UNIQUE(observation_tracker_id,horizon_sessions));
CREATE TABLE IF NOT EXISTS __SCHEMA__.trade_extrema(trade_leg_id uuid PRIMARY KEY REFERENCES __SCHEMA__.trade_legs, highest_favourable_price numeric(24,8), lowest_adverse_price numeric(24,8), mfe numeric(18,10), mae numeric(18,10), peak_to_trough_drawdown numeric(18,10), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS __SCHEMA__.valuation_snapshots(valuation_snapshot_id bigserial PRIMARY KEY, trade_group_id uuid NOT NULL REFERENCES __SCHEMA__.trade_groups, valued_at timestamptz NOT NULL, quality text NOT NULL, market_value numeric(24,8), unrealised_pnl numeric(24,8), source_refs jsonb NOT NULL, UNIQUE(trade_group_id,valued_at));
CREATE TABLE IF NOT EXISTS __SCHEMA__.instrument_monitor_cursors(exchange text NOT NULL, instrument_token text NOT NULL, last_bar_ts timestamptz, last_bar_id text, lease_owner text, lease_expires_at timestamptz, updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(exchange,instrument_token));
CREATE TABLE IF NOT EXISTS __SCHEMA__.processed_market_bars(exchange text NOT NULL, instrument_token text NOT NULL, source_bar_id text NOT NULL, bar_ts timestamptz NOT NULL, source_revision text, processed_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(exchange,instrument_token,source_bar_id));
CREATE TABLE IF NOT EXISTS __SCHEMA__.data_quality_incidents(incident_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), exchange text, instrument_token text, incident_type text NOT NULL, status text NOT NULL, detected_at timestamptz NOT NULL DEFAULT now(), recovered_at timestamptz, detail jsonb NOT NULL, UNIQUE(exchange,instrument_token,incident_type,status));

CREATE TABLE IF NOT EXISTS __SCHEMA__.pnl_ledger(pnl_ledger_id bigserial PRIMARY KEY, account_id text NOT NULL REFERENCES __SCHEMA__.accounts, trade_group_id uuid, trade_leg_id uuid, entry_kind text NOT NULL, amount numeric(24,8) NOT NULL, currency text NOT NULL DEFAULT 'INR', effective_at timestamptz NOT NULL, reversal_of bigint REFERENCES __SCHEMA__.pnl_ledger, event_id uuid, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS __SCHEMA__.charge_ledger(charge_ledger_id bigserial PRIMARY KEY, account_id text NOT NULL, trade_group_id uuid, trade_leg_id uuid, charge_kind text NOT NULL, amount numeric(24,8) NOT NULL CHECK(amount>=0), cost_profile_id text NOT NULL, effective_at timestamptz NOT NULL, reversal_of bigint REFERENCES __SCHEMA__.charge_ledger);
CREATE TABLE IF NOT EXISTS __SCHEMA__.income_tax_provision_ledger(tax_ledger_id bigserial PRIMARY KEY, account_id text NOT NULL, trade_group_id uuid, tax_profile_id text NOT NULL, taxable_net_profit numeric(24,8) NOT NULL, provision_amount numeric(24,8) NOT NULL CHECK(provision_amount>=0), effective_at timestamptz NOT NULL, reversal_of bigint REFERENCES __SCHEMA__.income_tax_provision_ledger);
CREATE TABLE IF NOT EXISTS __SCHEMA__.account_equity_snapshots(account_id text NOT NULL REFERENCES __SCHEMA__.accounts, snapshot_at timestamptz NOT NULL, cash numeric(24,8) NOT NULL, reserved numeric(24,8) NOT NULL, market_value numeric(24,8) NOT NULL, realised_pnl numeric(24,8) NOT NULL, unrealised_pnl numeric(24,8) NOT NULL, costs numeric(24,8) NOT NULL, tax_provision numeric(24,8) NOT NULL, equity numeric(24,8) NOT NULL, drawdown numeric(18,10) NOT NULL, PRIMARY KEY(account_id,snapshot_at));
CREATE TABLE IF NOT EXISTS __SCHEMA__.capital_reservations(capital_reservation_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id text NOT NULL REFERENCES __SCHEMA__.accounts, trade_group_id uuid NOT NULL REFERENCES __SCHEMA__.trade_groups, amount numeric(24,8) NOT NULL CHECK(amount>=0), basis_status text NOT NULL, status text NOT NULL, reserved_at timestamptz NOT NULL DEFAULT now(), released_at timestamptz);

CREATE TABLE IF NOT EXISTS __SCHEMA__.trade_events(event_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), aggregate_type text NOT NULL, aggregate_id uuid NOT NULL, sequence bigint NOT NULL, event_type text NOT NULL, correlation_id uuid NOT NULL, subject text NOT NULL, event_time timestamptz NOT NULL DEFAULT now(), payload jsonb NOT NULL, UNIQUE(aggregate_id,sequence));
CREATE INDEX IF NOT EXISTS trade_events_aggregate_idx ON __SCHEMA__.trade_events(aggregate_id,sequence);
CREATE TABLE IF NOT EXISTS __SCHEMA__.webhook_outbox(outbox_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), event_id uuid NOT NULL REFERENCES __SCHEMA__.trade_events, subscription_id uuid REFERENCES __SCHEMA__.webhook_subscriptions, status text NOT NULL DEFAULT 'PENDING', attempt_count int NOT NULL DEFAULT 0, available_at timestamptz NOT NULL DEFAULT now(), lease_owner text, lease_expires_at timestamptz, delivered_at timestamptz, last_error text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(event_id,subscription_id));
CREATE INDEX IF NOT EXISTS webhook_outbox_claim_idx ON __SCHEMA__.webhook_outbox(status,available_at);
CREATE TABLE IF NOT EXISTS __SCHEMA__.webhook_delivery_attempts(delivery_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), outbox_id uuid NOT NULL REFERENCES __SCHEMA__.webhook_outbox, attempt_number int NOT NULL, started_at timestamptz NOT NULL, completed_at timestamptz, response_status int, response_body_excerpt text, error_class text, duration_ms int, UNIQUE(outbox_id,attempt_number));
CREATE TABLE IF NOT EXISTS __SCHEMA__.webhook_dead_letters(dead_letter_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), outbox_id uuid NOT NULL UNIQUE REFERENCES __SCHEMA__.webhook_outbox, event_id uuid NOT NULL, failed_at timestamptz NOT NULL DEFAULT now(), reason text NOT NULL, replay_count int NOT NULL DEFAULT 0, last_replayed_at timestamptz);

CREATE TABLE IF NOT EXISTS __SCHEMA__.summary_runs(summary_run_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id text NOT NULL, summary_type text NOT NULL, period_start date NOT NULL, period_end date NOT NULL, revision int NOT NULL DEFAULT 1, status text NOT NULL, replaces_run_id uuid, started_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, UNIQUE(account_id,summary_type,period_start,period_end,revision));
CREATE TABLE IF NOT EXISTS __SCHEMA__.daily_summaries(summary_run_id uuid PRIMARY KEY REFERENCES __SCHEMA__.summary_runs, session_date date NOT NULL, activity_status text NOT NULL, metrics jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS __SCHEMA__.weekly_summaries(summary_run_id uuid PRIMARY KEY REFERENCES __SCHEMA__.summary_runs, week_start date NOT NULL, week_end date NOT NULL, metrics jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS __SCHEMA__.reconciliation_runs(reconciliation_run_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id text, started_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, status text NOT NULL, metrics jsonb NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS __SCHEMA__.reconciliation_findings(finding_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), reconciliation_run_id uuid NOT NULL REFERENCES __SCHEMA__.reconciliation_runs, severity text NOT NULL, finding_type text NOT NULL, aggregate_id uuid, detail jsonb NOT NULL, resolved_at timestamptz);
CREATE TABLE IF NOT EXISTS __SCHEMA__.audit_log(audit_id bigserial PRIMARY KEY, occurred_at timestamptz NOT NULL DEFAULT now(), actor text NOT NULL, action text NOT NULL, aggregate_type text, aggregate_id uuid, correlation_id uuid, before_state jsonb, after_state jsonb, source_reference jsonb, calculation_version text);

CREATE OR REPLACE VIEW __SCHEMA__.v_open_trade_groups AS SELECT * FROM __SCHEMA__.trade_groups WHERE status IN ('BUILDING','PENDING_ENTRY','PARTIALLY_OPEN','OPEN','PARTIALLY_CLOSED','AWAITING_SETTLEMENT');
CREATE OR REPLACE VIEW __SCHEMA__.v_open_trade_legs AS SELECT l.*,i.instrument_id,i.symbol,i.underlying FROM __SCHEMA__.trade_legs l JOIN __SCHEMA__.instrument_snapshots i USING(instrument_snapshot_id) WHERE l.remaining_quantity>0;
CREATE OR REPLACE VIEW __SCHEMA__.v_trade_execution_performance AS SELECT g.trade_group_id,g.account_id,g.strategy_id,g.status,COALESCE(sum(p.realised_pnl),0) realised_pnl,COALESCE(sum(p.unrealised_pnl),0) unrealised_pnl FROM __SCHEMA__.trade_groups g LEFT JOIN __SCHEMA__.trade_legs l USING(trade_group_id) LEFT JOIN __SCHEMA__.positions p USING(trade_leg_id) GROUP BY g.trade_group_id;
CREATE OR REPLACE VIEW __SCHEMA__.v_target_track_results AS
 SELECT g.trade_group_id,g.strategy_id,d.target_code,d.lifecycle,d.target_pct,
        t.status,t.first_hit_at,h.gross_pnl,h.after_tax_pnl
 FROM __SCHEMA__.target_tracks t
 JOIN __SCHEMA__.target_definitions d ON d.target_definition_id=t.target_definition_id
 JOIN __SCHEMA__.trade_legs l ON l.trade_leg_id=t.trade_leg_id
 JOIN __SCHEMA__.trade_groups g ON g.trade_group_id=l.trade_group_id
 LEFT JOIN __SCHEMA__.target_hits h ON h.target_track_id=t.target_track_id;
CREATE OR REPLACE VIEW __SCHEMA__.v_strategy_daily_performance AS SELECT g.strategy_id,(e.effective_at AT TIME ZONE 'Asia/Kolkata')::date session_date,sum(e.amount) pnl FROM __SCHEMA__.pnl_ledger e JOIN __SCHEMA__.trade_groups g USING(trade_group_id) GROUP BY 1,2;
CREATE OR REPLACE VIEW __SCHEMA__.v_strategy_weekly_performance AS SELECT strategy_id,date_trunc('week',session_date)::date week_start,sum(pnl) pnl FROM __SCHEMA__.v_strategy_daily_performance GROUP BY 1,2;
CREATE OR REPLACE VIEW __SCHEMA__.v_account_equity_curve AS SELECT * FROM __SCHEMA__.account_equity_snapshots;
CREATE OR REPLACE VIEW __SCHEMA__.v_webhook_delivery_health AS SELECT status,count(*) row_count,min(created_at) oldest FROM __SCHEMA__.webhook_outbox GROUP BY status;
CREATE OR REPLACE VIEW __SCHEMA__.v_data_freshness AS SELECT exchange,instrument_token,last_bar_ts,now()-last_bar_ts lag FROM __SCHEMA__.instrument_monitor_cursors;
CREATE OR REPLACE VIEW __SCHEMA__.v_option_group_performance AS SELECT * FROM __SCHEMA__.v_trade_execution_performance p WHERE EXISTS(SELECT 1 FROM __SCHEMA__.trade_groups g WHERE g.trade_group_id=p.trade_group_id AND g.asset_class='OPTION');

INSERT INTO __SCHEMA__.accounts(account_id,opening_cash,available_cash) VALUES ('paper-main',1600000,1600000) ON CONFLICT DO NOTHING;
INSERT INTO __SCHEMA__.tax_profiles(tax_profile_id,scope,positive_profit_rate,description) VALUES ('management-profit-tax-35pct','PER_TRADE_GROUP_POSITIVE_NET_PROFIT',0.35,'Configurable management provision; not legal tax advice') ON CONFLICT DO NOTHING;
INSERT INTO __SCHEMA__.cost_profiles(
 cost_profile_id,version,asset_class,exchange,segment,effective_from,enabled,rates,source_url,verified_at
) VALUES (
 'india-equity-current',1,'EQUITY','NSE','CASH','2026-03-01',true,
 '{"brokerage_flat_per_order":"20.00","exchange_turnover_rate":"0.0000307","sebi_turnover_rate":"0.000001","stt_sell_rate":"0.001","stamp_buy_rate":"0.00015","gst_rate":"0.18"}',
 'https://nsearchives.nseindia.com/content/circulars/FA73061.pdf',now()
) ON CONFLICT DO NOTHING;
INSERT INTO __SCHEMA__.cost_profiles(
 cost_profile_id,version,asset_class,exchange,segment,effective_from,enabled,rates,source_url,verified_at
) VALUES (
 'india-options-current',1,'OPTION','NFO','OPT','2026-04-01',true,
 '{"brokerage_flat_per_order":"20.00","exchange_turnover_rate":"0.0003553","sebi_turnover_rate":"0.000001","stt_sell_rate":"0.0015","stamp_buy_rate":"0.00003","gst_rate":"0.18"}',
 'https://www.nseindia.com/static/products-services/equity-derivatives-securities-transaction-tax',now()
) ON CONFLICT DO NOTHING;
