# Project-wide Gradle settings.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the Gradle Daemon.
# Setting a higher heap size helps avoid OutOfMemoryError during builds.
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8

# AndroidX is enabled by default in new projects
android.useAndroidX=true

# Enables parallel execution of Gradle tasks
org.gradle.parallel=true

# Caching for faster builds
org.gradle.caching=true
