create table if not exists nse_intraday.security_minute_feature (
  trade_date date not null,
  minute_ts timestamptz not null,
  symbol text not null,
  sector_name text,
  universe_weight numeric(18,8),
  last_price numeric(18,6) not null,
  prev_close numeric(18,6),
  session_open numeric(18,6),
  session_high_so_far numeric(18,6),
  session_low_so_far numeric(18,6),
  day_vwap numeric(18,6),
  cum_volume bigint,
  cum_turnover numeric(20,2),
  change_pct_from_prev_close numeric(18,6),
  change_pct_from_open numeric(18,6),
  change_pct_5m numeric(18,6),
  change_pct_15m numeric(18,6),
  change_pct_30m numeric(18,6),
  vwap_dev_bps numeric(18,6),
  above_vwap boolean,
  open_range_high_15 numeric(18,6),
  open_range_low_15 numeric(18,6),
  above_open_range_high boolean,
  below_open_range_low boolean,
  range_position_pct numeric(18,6),
  volume_ratio_day numeric(18,6),
  minute_no integer not null,
  generated_at timestamptz not null default now(),
  primary key (trade_date, minute_ts, symbol)
) partition by range (trade_date);

create index if not exists idx_security_minute_feature_symbol_minute
  on nse_intraday.security_minute_feature (symbol, minute_ts desc);

create table if not exists nse_intraday.market_minute_feature (
  trade_date date not null,
  minute_ts timestamptz not null,
  index_code text not null,
  index_name text not null,
  last_price numeric(18,6) not null,
  prev_close numeric(18,6),
  session_open numeric(18,6),
  session_high_so_far numeric(18,6),
  session_low_so_far numeric(18,6),
  change_pct_from_prev_close numeric(18,6),
  change_pct_from_open numeric(18,6),
  change_pct_5m numeric(18,6),
  change_pct_15m numeric(18,6),
  change_pct_30m numeric(18,6),
  gap_pct numeric(18,6),
  open_range_high_15 numeric(18,6),
  open_range_low_15 numeric(18,6),
  open_range_15_pct numeric(18,6),
  breadth_up_pct numeric(18,6),
  breadth_above_vwap_pct numeric(18,6),
  breadth_above_or_high_pct numeric(18,6),
  breadth_below_or_low_pct numeric(18,6),
  dispersion_pct numeric(18,6),
  sign_agreement_pct numeric(18,6),
  weighted_participation_pct numeric(18,6),
  top10_concentration_pct numeric(18,6),
  minute_no integer not null,
  generated_at timestamptz not null default now(),
  primary key (trade_date, minute_ts, index_code)
) partition by range (trade_date);

create index if not exists idx_market_minute_feature_code_minute
  on nse_intraday.market_minute_feature (index_code, minute_ts desc);

create table if not exists nse_intraday.stock_intraday_live (
  trade_date date not null,
  as_of_ts timestamptz not null,
  symbol text not null,
  sector_name text,
  last_price numeric(18,6),
  change_pct_from_prev_close numeric(18,6),
  change_pct_from_open numeric(18,6),
  change_pct_15m numeric(18,6),
  vwap_dev_bps numeric(18,6),
  relative_strength_bps numeric(18,6),
  above_vwap boolean,
  above_open_range_high boolean,
  below_open_range_low boolean,
  volume_ratio_day numeric(18,6),
  continuation_score numeric(18,6),
  weakness_score numeric(18,6),
  mean_reversion_score numeric(18,6),
  reversal_score numeric(18,6),
  dominant_signal text,
  direction text not null default 'neutral',
  accent_token text not null default 'white',
  tags_json jsonb not null default '[]'::jsonb,
  conclusion text,
  payload_json jsonb not null default '{}'::jsonb,
  generated_at timestamptz not null default now(),
  primary key (trade_date, symbol)
);

create index if not exists idx_stock_intraday_live_signal
  on nse_intraday.stock_intraday_live (trade_date desc, dominant_signal, direction, continuation_score desc);

create table if not exists nse_intraday.market_session_summary (
  trade_date date not null,
  index_code text not null,
  as_of_ts timestamptz not null,
  index_name text not null,
  last_price numeric(18,6),
  prev_close numeric(18,6),
  change_pct numeric(18,6),
  gap_pct numeric(18,6),
  session_range_pct numeric(18,6),
  close_location_pct numeric(18,6),
  open_range_15_pct numeric(18,6),
  breadth_up_pct numeric(18,6),
  breadth_above_vwap_pct numeric(18,6),
  breadth_above_or_high_pct numeric(18,6),
  breadth_below_or_low_pct numeric(18,6),
  dispersion_pct numeric(18,6),
  weighted_participation_pct numeric(18,6),
  top10_concentration_pct numeric(18,6),
  participation_label text,
  primary_state text,
  secondary_states_json jsonb not null default '[]'::jsonb,
  confidence_score numeric(18,6),
  gap_filled boolean not null default false,
  failed_open boolean not null default false,
  late_day_reversal boolean not null default false,
  high_volatility_chop boolean not null default false,
  narrow_leadership boolean not null default false,
  broad_participation boolean not null default false,
  narrative text,
  payload_json jsonb not null default '{}'::jsonb,
  generated_at timestamptz not null default now(),
  primary key (trade_date, index_code)
);
