from __future__ import annotations

import unittest
from unittest.mock import patch

import pandas as pd

from nse_fii_services.parsers import parse_fii_stats_excel, parse_participant_csv


SAMPLE_PARTICIPANT_CSV = b"""This file generated by NSE\nClient Type,Future Index Long,Future Index Short\nClient,10,20\nDII,11,21\nFII,12,22\nPro,13,23\nTOTAL,46,86\nNote:,ignore,ignore\n"""


class ParserTests(unittest.TestCase):
    def test_parse_participant_csv(self) -> None:
        df = parse_participant_csv(SAMPLE_PARTICIPANT_CSV)
        self.assertEqual(list(df.columns), ["Client Type", "Future Index Long", "Future Index Short"])
        self.assertEqual(df.iloc[0, 0], "Client")
        self.assertEqual(len(df), 5)
        self.assertEqual(df.iloc[-1, 0], "TOTAL")

    @patch("nse_fii_services.parsers.pd.read_excel")
    def test_parse_fii_stats_excel_filters_rows(self, mock_read_excel) -> None:
        mock_read_excel.return_value = pd.DataFrame(
            [
                ["INDEX FUTURES", 1, 2, 3, 4, 5, 6],
                ["STOCK FUTURES", 7, 8, 9, 10, 11, 12],
                ["Random footer", None, None, None, None, None, None],
            ]
        )
        df = parse_fii_stats_excel(b"fake xls bytes")
        self.assertEqual(list(df["fii_derivatives"]), ["INDEX FUTURES", "STOCK FUTURES"])
        self.assertEqual(list(df.columns), [
            "fii_derivatives",
            "buy_contracts",
            "buy_value_in_Cr",
            "sell_contracts",
            "sell_value_in_Cr",
            "open_contracts",
            "open_contracts_value_in_Cr",
        ])

    @patch("nse_fii_services.parsers.pd.read_excel", side_effect=ImportError("xlrd missing"))
    def test_parse_fii_stats_excel_gives_helpful_error(self, _mock_read_excel) -> None:
        with self.assertRaises(ImportError) as ctx:
            parse_fii_stats_excel(b"fake xls bytes")
        self.assertIn("pip install xlrd", str(ctx.exception))


if __name__ == "__main__":
    unittest.main()
