from __future__ import annotations

import unittest
from unittest.mock import patch

import pandas as pd

from nse_fii_services.parsers import FOVOLT_SCHEMA, parse_fii_stats_excel, parse_fovolt_csv, parse_participant_csv, rank_fovolt_rows


SAMPLE_PARTICIPANT_CSV = b"""This file generated by NSE\nClient Type,Future Index Long,Future Index Short\nClient,10,20\nDII,11,21\nFII,12,22\nPro,13,23\nTOTAL,46,86\nNote:,ignore,ignore\n"""


class ParserTests(unittest.TestCase):
    def test_fovolt_uses_exact_strict_physical_delta(self) -> None:
        header = ",".join(name for _key, name in FOVOLT_SCHEMA)
        def row(symbol: str, previous: str, current: str) -> str:
            values = ["10-Sep-26", symbol, "100", "99", "0.01", "0.02", "0.02", "0.38", "101", "100", "0.01", previous, current, "0.38", "0.02", "0.38"]
            return ",".join(values)
        raw = (header + "\n" + row("PASS", "0.02000000", "0.02010001") + "\n" + row("EQUAL", "0.02000000", "0.02010000") + "\n" + row("DOWN", "0.02020000", "0.02000000") + "\n").encode()
        ranked = rank_fovolt_rows(parse_fovolt_csv(raw))
        by_symbol = {item["symbol"]: item for item in ranked}
        self.assertTrue(by_symbol["PASS"]["rule_match"])
        self.assertFalse(by_symbol["EQUAL"]["rule_match"])
        self.assertFalse(by_symbol["DOWN"]["rule_match"])
        self.assertEqual(str(by_symbol["PASS"]["delta_futures_vol_raw"]), "0.00010001")
        self.assertEqual(str(by_symbol["PASS"]["delta_futures_vol_bp"]), "1.00010000")

    def test_fovolt_rejects_duplicate_identity_and_html(self) -> None:
        with self.assertRaisesRegex(ValueError, "not HTML"):
            parse_fovolt_csv(b"<html>blocked</html>")
    def test_parse_participant_csv(self) -> None:
        df = parse_participant_csv(SAMPLE_PARTICIPANT_CSV)
        self.assertEqual(list(df.columns), ["Client Type", "Future Index Long", "Future Index Short"])
        self.assertEqual(df.iloc[0, 0], "Client")
        self.assertEqual(len(df), 5)
        self.assertEqual(df.iloc[-1, 0], "TOTAL")

    @patch("nse_fii_services.parsers.pd.read_excel")
    def test_parse_fii_stats_excel_filters_rows(self, mock_read_excel) -> None:
        mock_read_excel.return_value = pd.DataFrame(
            [
                ["INDEX FUTURES", 1, 2, 3, 4, 5, 6],
                ["STOCK FUTURES", 7, 8, 9, 10, 11, 12],
                ["Random footer", None, None, None, None, None, None],
            ]
        )
        df = parse_fii_stats_excel(bytes.fromhex("d0cf11e0a1b11ae1"))
        self.assertEqual(list(df["fii_derivatives"]), ["INDEX FUTURES", "STOCK FUTURES"])
        self.assertEqual(list(df.columns), [
            "fii_derivatives",
            "buy_contracts",
            "buy_value_in_Cr",
            "sell_contracts",
            "sell_value_in_Cr",
            "open_contracts",
            "open_contracts_value_in_Cr",
        ])

    @patch("nse_fii_services.parsers.pd.read_excel", side_effect=ImportError("xlrd missing"))
    def test_parse_fii_stats_excel_gives_helpful_error(self, _mock_read_excel) -> None:
        with self.assertRaises(ImportError) as ctx:
            parse_fii_stats_excel(bytes.fromhex("d0cf11e0a1b11ae1"))
        self.assertIn("pip install xlrd", str(ctx.exception))

    def test_html_masquerading_as_xls_rejected(self):
        with self.assertRaises(ValueError):
            parse_fii_stats_excel(b"<html>Access denied</html>")

    def test_quoted_padded_participant_header(self):
        frame = parse_participant_csv(b'Preamble\n" Client Type ",Future Index Long,Future Index Short\nFII,1,2\n')
        self.assertEqual(frame.iloc[0, 0], "FII")


if __name__ == "__main__":
    unittest.main()
