apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    uid: postgres
    access: proxy
    url: postgres:5432
    database: tradingdb
    user: trader
    isDefault: true
    secureJsonData:
      password: CHANGE_ME_POSTGRES_PASSWORD
    jsonData:
      database: tradingdb
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
