import { useCallback, useEffect, useState, type FormEvent } from "react";
import { fetchOiisLiveDashboard, mutateOiisLive, type OiisLiveDashboard } from "../lib/api";
import { AnalyticsHeader, STRATEGY_SECTION_TABS } from "./AnalyticsChrome";
import styles from "./OiisLivePage.module.css";

const empty = { symbol: "", active: true, entryEnabled: false, rsiMax: 30, willrMax: -80, notes: "" };

function value(row: Record<string, any>, key: string) { const item=row[key]; return item == null ? "—" : String(item); }
function number(row: Record<string, any>, key: string, digits=2) { const item=Number(row[key]); return Number.isFinite(item) ? item.toFixed(digits) : "—"; }

export function OiisLivePage() {
  const [data,setData]=useState<OiisLiveDashboard|null>(null); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const [tradeDate,setTradeDate]=useState(""); const [form,setForm]=useState(empty); const [editing,setEditing]=useState<string|null>(null);
  const load=useCallback(async(date?:string)=>{try{setError("");const next=await fetchOiisLiveDashboard(date);setData(next);if(next.tradeDate)setTradeDate(next.tradeDate)}catch(e){setError(e instanceof Error?e.message:String(e))}},[]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(tradeDate||undefined),30000);return()=>window.clearInterval(timer)},[load,tradeDate]);
  const run=async(command:string)=>{setBusy(true);try{await mutateOiisLive("/commands","POST",{command});await load(tradeDate)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);try{const body={...form,tradeDate};await mutateOiisLive(editing?`/watchlist/${editing}`:"/watchlist",editing?"PATCH":"POST",body);setEditing(null);setForm(empty);await load(tradeDate)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
  const edit=(row:Record<string,any>)=>{setEditing(String(row.watchlist_item_id));setForm({symbol:String(row.symbol),active:Boolean(row.active),entryEnabled:Boolean(row.entry_enabled),rsiMax:Number(row.rsi_max),willrMax:Number(row.willr_max),notes:String(row.notes??"")})};
  const remove=async(id:string)=>{setBusy(true);try{await mutateOiisLive(`/watchlist/${id}`,"DELETE");await load(tradeDate)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
  const watch=data?.watchlist??[]; const eligible=watch.filter(row=>row.entry_enabled&&row.active).length; const accepted=(data?.entries??[]).filter(row=>row.status==="ACCEPTED"||row.status==="FILLED").length;
  return <div className={styles.page}>
    <AnalyticsHeader title="OIIS Live Watchlist" subtitle="Daily opportunity selection, one-entry-per-stock monitoring, paper execution and operational diagnostics." sectionTabs={[...STRATEGY_SECTION_TABS]}/>
    <section className={styles.hero}><div><h1>Stocks selected for paper entry</h1><p>The board separates monitoring candidates from canonical trade permission. A permitted stock can enter only once per trading day when one-minute RSI is below 30 and Williams %R is below −80. Actual exits remain +0.30% intraday, then +1% swing from the next session.</p></div><span className={styles.paper}>PAPER ONLY</span></section>
    {error&&<div className={styles.error}>{error}</div>}
    <section className={styles.stats}><div className={styles.card}><span>Trade date</span><strong>{data?.tradeDate??"—"}</strong></div><div className={styles.card}><span>Watchlist</span><strong>{watch.length}</strong></div><div className={styles.card}><span>Entry enabled</span><strong>{eligible}</strong></div><div className={styles.card}><span>Accepted entries</span><strong>{accepted}</strong></div><div className={styles.card}><span>Latest selector</span><strong>{value(data?.runs?.[0]??{},"status")}</strong></div></section>
    <section className={styles.panel}><div className={styles.toolbar}><div className={styles.toolbarGroup}><label>Date <select value={tradeDate} onChange={e=>{setTradeDate(e.target.value);void load(e.target.value)}}>{(data?.availableDates??[]).map(row=>{const d=String(row.trade_date).slice(0,10);return <option key={d}>{d}</option>})}</select></label><button className={styles.button} disabled={busy} onClick={()=>void run("RUN_SELECTION")}>Run selection</button><button className={styles.buttonSecondary} disabled={busy} onClick={()=>void run("RECONCILE")}>Reconcile</button></div><span className={styles.muted}>Refreshes every 30 seconds</span></div>
      <form className={styles.editor} onSubmit={submit}><label>Symbol<input value={form.symbol} disabled={!!editing} onChange={e=>setForm({...form,symbol:e.target.value.toUpperCase()})} required/></label><label>RSI below<input type="number" step="0.1" value={form.rsiMax} onChange={e=>setForm({...form,rsiMax:Number(e.target.value)})}/></label><label>WILLR below<input type="number" step="0.1" value={form.willrMax} onChange={e=>setForm({...form,willrMax:Number(e.target.value)})}/></label><label>Notes<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><label className={styles.check}><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Active</label><label className={styles.check}><input type="checkbox" checked={form.entryEnabled} onChange={e=>setForm({...form,entryEnabled:e.target.checked})}/>Entry enabled</label><button className={styles.button} disabled={busy}>{editing?"Save changes":"Add monitor"}</button>{editing&&<button type="button" className={styles.buttonSecondary} onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}</form>
    </section>
    <section className={styles.panel}><h2>Selected candidates</h2><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Rank</th><th>Stock</th><th>Level</th><th>Canonical status</th><th>O</th><th>X</th><th>DQ</th><th>Buy reference</th><th>RSI / WILLR trigger</th><th>Entry</th><th>Paper state</th><th>Actions</th></tr></thead><tbody>{watch.map(row=><tr key={row.watchlist_item_id}><td>{value(row,"rank")}</td><td><strong>{row.symbol}</strong><br/><span className={styles.muted}>{value(row,"sector")}</span></td><td><span className={styles.pill} data-state={row.daily_level}>{value(row,"daily_level")}</span></td><td>{value(row,"canonical_status")}</td><td>{number(row,"ofactor")}</td><td>{number(row,"xfactor_snapshot")}</td><td>{number(row,"data_quality")}</td><td>₹{number(row,"buy_limit")}</td><td>&lt; {number(row,"rsi_max",1)} / &lt; {number(row,"willr_max",1)}</td><td>{row.entry_enabled?"Enabled":"Monitor only"}</td><td><span className={styles.pill} data-state={row.entry_status}>{value(row,"entry_status")}</span></td><td><button className={styles.buttonSecondary} onClick={()=>edit(row)}>Edit</button> <button className={styles.buttonDanger} onClick={()=>void remove(String(row.watchlist_item_id))}>Remove</button></td></tr>)}</tbody></table></div>{watch.length===0&&<p className={styles.muted}>No candidates stored for this date.</p>}</section>
    <section className={styles.panel}><h2>Service diagnostics</h2><p className={styles.muted}>Application readiness is shown without exposing the privileged Docker socket to the web container.</p><div className={styles.health}>{(data?.diagnostics??[]).map(row=><div className={styles.healthItem} key={row.service_name}><div><strong>{row.service_name}</strong><div className={styles.muted}>Updated {value(row,"age_seconds")}s ago</div></div><span className={styles.pill} data-state={row.status}>{row.status}</span></div>)}</div>
      <h3>Data freshness and durable queues</h3><div className={styles.health}><div className={styles.healthItem}><div><strong>SmartAPI minute bars</strong><div className={styles.muted}>{value(data?.freshness??{},"latest_minute_bar")}</div></div><span>{value(data?.freshness??{},"latest_minute_symbols")} symbols</span></div><div className={styles.healthItem}><div><strong>NSE daily / stock regimes</strong><div className={styles.muted}>{value(data?.freshness??{},"latest_nse_eod")} / {value(data?.freshness??{},"latest_stock_regime")}</div></div><span className={styles.pill} data-state="OK">Stored</span></div><div className={styles.healthItem}><strong>Paper webhooks pending</strong><span>{value(data?.queues??{},"paper_outbox_pending")}</span></div><div className={styles.healthItem}><strong>OIIS errors pending</strong><span>{value(data?.queues??{},"oiis_errors_pending")}</span></div><div className={styles.healthItem}><strong>Entry retries pending</strong><span>{value(data?.queues??{},"entry_retries_pending")}</span></div><div className={styles.healthItem}><strong>Historical dead letters</strong><span>{value(data?.queues??{},"paper_dead_letters")}</span></div></div>
      <h3>Paper-trading state</h3><div className={styles.health}>{(data?.paper??[]).map(row=><div className={styles.healthItem} key={row.status}><strong>{row.status}</strong><span>{row.count}</span></div>)}</div><h3>Error delivery ledger</h3><div className={styles.health}>{(data?.errors??[]).map(row=><div className={styles.healthItem} key={`${row.severity}-${row.status}`}><strong>{row.severity} / {row.status}</strong><span>{row.count}</span></div>)}</div></section>
  </div>
}
