import { useMemo, useState } from 'react';
import type { EChartsOption } from 'echarts';
import { EChartSurface } from '../components/visual/EChartSurface';
import { analyzerCsv, analyzerGroups, analyzerParameters, analyzerTrade, correlation, densityPlotValue, histogram, summarizeOutcomes, type OutcomeBasis, type PaperRow } from '../lib/paperAnalyzer';
import styles from './PaperTradeAnalyzer.module.css';

const fmt=(value:number|null,digits=2)=>value==null?'—':value.toLocaleString('en-IN',{maximumFractionDigits:digits});
const signed=(value:number|null)=>value==null?'—':`${value>0?'+':''}${fmt(value)}`;
const colour=(value:number|null)=>value==null||value===0?'#64748b':value>0?'#17834f':'#c7473d';
const basisNames:Record<OutcomeBasis,string>={closed:'Closed trades · realised net',open:'Open positions · unrealised gross',eod:'Entry-day EOD · hypothetical gross'};
function save(name:string,body:string,mime:string){const url=URL.createObjectURL(new Blob([body],{type:mime}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}

export function PaperTradeAnalyzer({trades,onSelect,loading,asOf}:{trades:PaperRow[];onSelect:(trade:PaperRow)=>void;loading:boolean;asOf:string|null}) {
  const [basis,setBasis]=useState<OutcomeBasis>('closed');
  const [parameter,setParameter]=useState('rsi');
  const [group,setGroup]=useState('strategy');
  const [strategy,setStrategy]=useState('ALL');
  const [direction,setDirection]=useState('ALL');
  const [search,setSearch]=useState('');
  const [from,setFrom]=useState(''),[to,setTo]=useState('');
  const [density,setDensity]=useState(false);
  const model=useMemo(()=>trades.map(row=>analyzerTrade(row,basis)),[trades,basis]);
  const rows=useMemo(()=>model.filter(r=>(strategy==='ALL'||r.strategy===strategy)&&(direction==='ALL'||r.direction===direction)&&r.symbol.toLowerCase().includes(search.toLowerCase())&&(!from||r.day>=from)&&(!to||r.day<=to)),[model,strategy,direction,search,from,to]);
  const eligible=useMemo(()=>rows.filter(r=>r.outcome!=null&&!r.excluded),[rows]);
  const stats=useMemo(()=>summarizeOutcomes(rows),[rows]);
  const otherLanes=useMemo(()=>({closed:summarizeOutcomes(rows.map(r=>analyzerTrade(r.raw,'closed'))),open:summarizeOutcomes(rows.map(r=>analyzerTrade(r.raw,'open')))}),[rows]);
  const groups=useMemo(()=>analyzerGroups(rows,group,parameter),[rows,group,parameter]);
  const correlations=useMemo(()=>analyzerParameters.map(p=>({...p,...correlation(eligible.filter(r=>r.parameters[p.id]!=null).map(r=>[r.parameters[p.id]!,r.outcome!])),symbols:new Set(eligible.filter(r=>r.parameters[p.id]!=null).map(r=>r.symbol)).size})),[eligible]);
  const selected=correlations.find(p=>p.id===parameter)!;
  const exclusions=useMemo(()=>{const counts=new Map<string,number>();for(const r of rows)if(r.excluded)counts.set(r.excluded,(counts.get(r.excluded)??0)+1);return [...counts];},[rows]);
  const distribution=useMemo<EChartsOption>(()=>{const bins=histogram(eligible.map(r=>r.outcome!));return {animation:false,tooltip:{trigger:'axis',formatter:(items:any)=>{const b=bins[items[0]?.dataIndex];return b?`${fmt(b.low)}…${fmt(b.high)}%<br/>Trades: ${b.count}<br/>Density / percentage point: ${b.density.toExponential(2)}`:'';}},grid:{left:65,right:20,top:40,bottom:80},xAxis:{type:'category',name:'Outcome return % · equal-width bins',nameLocation:'middle',nameGap:55,axisLabel:{rotate:30},data:bins.map(b=>`${fmt(b.low)}…${fmt(b.high)}`)},yAxis:{type:'value',name:density?'Density / percentage point':'Trade count',min:0,axisLabel:{formatter:(v:number)=>density?v.toExponential(2):String(v)}},series:[{type:'bar',data:bins.map(b=>({value:density?densityPlotValue(b.density):b.count,itemStyle:{color:colour((b.low+b.high)/2)}}))}]};},[eligible,density]);
  const scatter=useMemo<EChartsOption>(()=>({animation:false,tooltip:{trigger:'item',renderMode:'richText',formatter:(p:any)=>`${p.value[2]}\n${selected.label}: ${fmt(p.value[0])} ${selected.unit}\nReturn: ${signed(p.value[1])}%`},grid:{left:65,right:25,top:25,bottom:60},xAxis:{type:'value',name:`${selected.label} (${selected.unit})`,nameLocation:'middle',nameGap:35,scale:true},yAxis:{type:'value',name:'Outcome return %',scale:true},series:[{type:'scatter',symbolSize:9,data:eligible.filter(r=>r.parameters[parameter]!=null).map(r=>({value:[r.parameters[parameter],r.outcome,r.symbol],itemStyle:{color:colour(r.outcome),opacity:.7}})),markLine:{silent:true,symbol:'none',data:[{yAxis:0}],lineStyle:{color:'#64748b',type:'dashed'}}}]}),[eligible,parameter,selected.label,selected.unit]);
  const heatmap=useMemo<EChartsOption>(()=>({animation:false,tooltip:{formatter:(p:any)=>`${correlations[p.value[1]].label}<br/>${p.value[0]===0?'Pearson':'Spearman'}: ${fmt(p.value[2],3)}<br/>Matched n=${correlations[p.value[1]].n}`},grid:{left:8,right:15,top:15,bottom:35},xAxis:{type:'category',data:['Pearson r','Spearman ρ']},yAxis:{type:'category',data:correlations.map(p=>p.label),axisLabel:{fontSize:11}},visualMap:{show:false,min:-1,max:1,inRange:{color:['#ca534b','#f0f3f6','#268451']}},series:[{type:'heatmap',label:{show:true,formatter:(p:any)=>fmt(p.value[2],2)},data:correlations.flatMap((p,i)=>[p.pearson==null?null:[0,i,p.pearson],p.spearman==null?null:[1,i,p.spearman]].filter(v=>v!=null))}]}),[correlations]);
  const ordered=useMemo(()=>[...rows].sort((a,b)=>(b.outcome??-Infinity)-(a.outcome??-Infinity)),[rows]);
  const exportReport=()=>save('paper-analyzer.json',JSON.stringify({asOf,basis,basisLabel:basisNames[basis],filters:{strategy,direction,search,from,to},parameter,group,stats,groups,correlations,exclusions,method:'Descriptive selected paper-equity legs; no causal or predictive validation. Closed net/open gross/hypothetical EOD never pooled.',trades:rows.map(r=>({id:r.id,symbol:r.symbol,outcome:r.outcome,pnl:r.pnl,excluded:r.excluded,parameters:r.parameters,source:r.raw}))},null,2),'application/json');
  return <section className={styles.analyzer} data-testid="paper-trade-analyzer">
    <header className={styles.heading}><div><small>PAPER TRADE ANALYSIS</small><h2>What is helping—and what is not?</h2><p>Compare recorded outcomes, parameter distributions and associations. Analysis only; no strategy or order changes.</p></div><div className={styles.controls}><button onClick={()=>save(`paper-analyzer-${basis}.csv`,analyzerCsv(rows,basis,asOf),'text/csv;charset=utf-8')}>Export CSV</button><button onClick={exportReport}>Export analysis JSON</button></div></header>
    <div className={styles.controls}>
      <label>Outcome basis<select aria-label="Outcome basis" value={basis} onChange={e=>setBasis(e.target.value as OutcomeBasis)}>{Object.entries(basisNames).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
      <label>Strategy / version<select value={strategy} onChange={e=>setStrategy(e.target.value)}><option value="ALL">All recorded strategies</option>{[...new Set(model.map(r=>r.strategy))].sort().map(s=><option key={s}>{s}</option>)}</select></label>
      <label>Direction<select value={direction} onChange={e=>setDirection(e.target.value)}><option value="ALL">Both directions</option><option>LONG</option><option>SHORT</option></select></label>
      <label>Stock<input placeholder="Search symbol" value={search} onChange={e=>setSearch(e.target.value)}/></label>
      <label>Entry from<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Entry through<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label>
    </div>
    <p className={styles.note}>Equity paper-trade legs only · {rows.length} selected / {trades.length} supplied · {stats.n} eligible outcomes · {stats.excluded} excluded · Last ledger refresh {asOf ? new Date(asOf).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})+' IST':'pending'}. {loading?'Complete ledger is still loading.':''}</p>
    <p className={styles.warning}><b>Do not read closed-trade win rate in isolation.</b> This selection has {otherLanes.closed.n} eligible closed legs with ₹{signed(otherLanes.closed.pnl)} booked net P/L, and {otherLanes.open.n} eligible open legs with ₹{signed(otherLanes.open.pnl)} remaining gross mark P/L. These have different cost bases and are not combined. Invalid/missing outcomes remain outside both totals; inspect exclusions below. This is not the whole-account reconciliation.</p>
    {basis==='open'&&<p role="status" className={styles.warning}>Open marks are provisional gross P/L on remaining quantity—not realised wins. Partial realised P/L is excluded. Check each mark timestamp in the trade inspector.</p>}
    {basis==='eod'&&<p role="status" className={styles.warning}>Hypothetical entry-day closing-price outcomes, not executed exits. No fees deducted. Only records with an available canonical EOD mark are included.</p>}
    <div className={styles.kpis}>
      <article><span>Eligible / distinct stocks</span><strong>{stats.n} / {stats.symbols}</strong><small>{stats.wins} positive · {stats.losses} negative · {stats.flat} flat</small></article>
      <article><span>Mean return</span><strong style={{color:colour(stats.mean)}}>{signed(stats.mean)}%</strong><small>Equal weight per trade leg; not portfolio CAGR</small></article>
      <article><span>Median return</span><strong>{signed(stats.median)}%</strong><small>Less sensitive to extreme outcomes</small></article>
      <article><span>Positive outcome rate</span><strong>{fmt(stats.winRate,1)}%</strong><small>Descriptive 95% range {fmt(stats.winLow,1)}–{fmt(stats.winHigh,1)}%</small></article>
      <article><span>{basis==='closed'?'Booked net P/L':basis==='open'?'Remaining gross mark P/L':'Hypothetical EOD gross P/L'}</span><strong style={{color:colour(stats.pnl)}}>₹{signed(stats.pnl)}</strong><small>{stats.indication}</small></article>
    </div>
    {!stats.n&&<p role="status">No eligible outcomes for these filters. Missing/open data is not converted into a loss or a zero.</p>}
    <div className={styles.charts}>
      <article><div className={styles.heading}><h3>Outcome distribution</h3><label><input type="checkbox" checked={density} onChange={e=>setDensity(e.target.checked)}/> Probability density</label></div>{stats.n?<EChartSurface ariaLabel="Paper outcome distribution" option={distribution} className={styles.chart}/>:<p>No outcome distribution available.</p>}<p className={styles.note}>Equal-width histogram; density area sums to one. Green/red bins indicate the return range, not strategy quality.</p></article>
      <article><h3>Parameter vs outcome</h3><label className={styles.controls}>Parameter<select aria-label="Parameter" value={parameter} onChange={e=>setParameter(e.target.value)}>{analyzerParameters.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label>{selected.n ? <EChartSurface ariaLabel="Paper parameter scatter" option={scatter} className={styles.chart}/>:<p>No timestamp-qualified parameter observations.</p>}<p className={styles.note}>Matched {selected.n}/{stats.n} · {selected.symbols} stocks · Pearson {fmt(selected.pearson,3)} · Spearman {fmt(selected.spearman,3)}. {selected.n<10?'Too few observations for a useful indication.':'In-sample association only; not proof this parameter works.'}</p></article>
    </div>
    <article><div className={styles.heading}><h3>Parameter / cohort comparison</h3><label>Compare by <select aria-label="Compare by" value={group} onChange={e=>setGroup(e.target.value)}>{[['strategy','Strategy / version'],['direction','Long / short'],['sector','Sector'],['hour','Entry hour IST'],['weekday','Entry weekday'],['parameter','Selected parameter quartiles']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>
      <p className={styles.note}>Sorted by observed average—not a recommendation. Groups below 10 outcomes are inconclusive. Early/later entry-date split: {groups.cutoff??'not available'} IST. This is a descriptive stability check, not an untouched validation set.</p>
      {group==='parameter'&&<p className={styles.note}>Dataset-relative Q1/Q2/Q3 boundaries: {groups.boundaries.map(v=>fmt(v??null)).join(' / ')} {selected.unit}. Equal values stay together; some quartiles may be empty.</p>}
      <div className={styles.table}><table><thead><tr>{['Group','N / stocks','Mean %','Median %','Positive %','Early mean / N','Later mean / N','Indication'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{groups.rows.map(r=><tr key={r.label}><td>{r.label}</td><td>{r.n} / {r.symbols}</td><td style={{color:colour(r.mean)}}>{signed(r.mean)}</td><td>{signed(r.median)}</td><td>{fmt(r.winRate,1)}</td><td>{signed(r.early.mean)} / {r.early.n}</td><td>{signed(r.later.mean)} / {r.later.n}</td><td>{r.indication}{r.early.n>=10&&r.later.n>=10&&r.early.mean!*r.later.mean!<0?' · direction reversed':r.early.n<10||r.later.n<10?' · stability sample too small':''}</td></tr>)}</tbody></table></div>
    </article>
    <div className={styles.charts}>
      <article><h3>Correlation map</h3><EChartSurface ariaLabel="Paper parameter correlation map" option={heatmap} className={styles.chart}/><div className={styles.scale} aria-label="Correlation colour scale from minus one to plus one"><span>−1</span><span>0</span><span>+1</span></div><p className={styles.note}>Green = positive association; red = negative association. Neither means good/bad. Blank = fewer than 3 matched observations or constant values. Outcomes and after-trade quality scores are not used as entry predictors.</p></article>
      <article><h3>Evidence coverage</h3><div className={styles.table}><table><thead><tr><th>Parameter</th><th>Matched / eligible</th><th>Stocks</th><th>Evidence</th></tr></thead><tbody>{correlations.map(p=><tr key={p.id}><td>{p.label}</td><td>{p.n} / {stats.n}</td><td>{p.symbols}</td><td>{p.n<10?'Insufficient sample':p.pearson==null?'No variation':'Descriptive only'}</td></tr>)}</tbody></table></div><h4>Excluded outcomes</h4>{exclusions.length?exclusions.map(([reason,count])=><p key={reason}>{reason}: <b>{count}</b></p>):<p>No outcome exclusions in this selection.</p>}</article>
    </div>
    <article><h3>Trade evidence · best to worst observed return</h3><p className={styles.note}>Select a trade for the existing full inspector, entry snapshot, costs and timestamps. All filtered rows are included in exports.</p><div className={styles.table}><table><thead><tr><th>Stock / evidence</th><th>Entry date</th><th>Direction</th><th>Outcome %</th><th>P/L ₹</th><th>{selected.label}</th><th>Eligibility</th></tr></thead><tbody>{ordered.map(r=><tr key={r.id}><td><button onClick={()=>onSelect(r.raw)}>{r.symbol}</button></td><td>{r.day||'—'}</td><td>{r.direction}</td><td style={{color:colour(r.outcome)}}>{signed(r.outcome)}</td><td>{signed(r.pnl)}</td><td>{fmt(r.parameters[parameter])}</td><td>{r.excluded??'Included'}</td></tr>)}</tbody></table></div></article>
    <details><summary>Methodology and limits</summary><p>Return = selected-basis P/L ÷ its entry notional × 100. Closed net uses the authoritative realised ledger; open gross uses only remaining quantity. EOD uses the existing hypothetical projection. Invalid source evidence is excluded.</p><p>RSI, volume, O/X factors, ATR and directional edge require an evidence timestamp at or before entry. Spread requires a non-negative immutable quote spread no more than 60 seconds before entry. Missing and late evidence are excluded pairwise, not zero-filled. Data-quality grades based on future outcomes are deliberately not predictors.</p><p>Correlation is Pearson linear association and Spearman rank association with average tied ranks. At least three variable matched pairs are required; fewer than ten outcomes are flagged. Multiple comparisons, selected-trade bias, market regime and repeated stocks/sessions can create misleading patterns. The win-rate range assumes independent observations and may understate uncertainty here. No causal conclusion, profitability guarantee, parameter optimisation or live rule change follows from this dashboard.</p></details>
  </section>;
}
