import {useState} from 'react';
import {Link} from 'react-router-dom';
import {horizons,Horizon,instrumentEvidence,number,numeric,Observation,side,textValue,time,windowEvidence} from '../lib/tradeObservation';
import {observationOptionPnl,scalperLink} from '../lib/optionPnl';
import styles from './TradingAnalyticsTradeLog.module.css';
export function TradeObservationPnl({row}:{row:Observation}) {
 const [h,setH]=useState<Horizon>('eod'); const [lots,setLots]=useState('1'); const [exit,setExit]=useState('endpoint');
 const count=number(lots),valid=count!==null&&Number.isSafeInteger(count)&&count>0; const link=scalperLink(row);
 const results=(['ce','pe'] as const).map(k=>{const result=observationOptionPnl(row,h,k,exit as 'endpoint'|'max'|'min',valid?count:0);return {instrument:k,lot:result.lotSize,qty:result.quantity,data:result.evidence,pnl:result.pnl};});
 return <section aria-label="Entry high low and hypothetical option P&L">
 <div className={styles.toolbar}><h3>From entry: high, low &amp; P&amp;L</h3>{link?<Link to={link}>Open stock + CE + PE in Scalper ↗</Link>:<span>Exact Scalper identity unavailable</span>}</div>
 <div className={styles.toolbar}><label>Outcome window <select aria-label="PnL window" value={h} onChange={e=>setH(e.target.value as Horizon)}>{horizons.map(v=><option key={v}>{v}</option>)}</select></label><label>Lots <input aria-label="Number of option lots" type="number" min="1" step="1" value={lots} onChange={e=>setLots(e.target.value)}/></label><label>Hypothetical exit <select aria-label="Hypothetical exit" value={exit} onChange={e=>setExit(e.target.value)}><option value="endpoint">Latest observed close</option><option value="max">Observed high</option><option value="min">Observed low</option></select></label><span>{textValue(windowEvidence(row,h).maturity)}{windowEvidence(row,h).maturity==='DEVELOPING'?' · So far':''}</span></div>
 <div className={styles.scroll} tabIndex={0} role="region" aria-label="Entry to high low values"><table><thead><tr><th>Instrument</th><th>Entry open</th><th>High since entry</th><th>Low since entry</th><th>Latest observed close</th></tr></thead><tbody>{['underlying','ce','pe'].map(k=>{const d=instrumentEvidence(row,h,k);return <tr key={k}><th>{k==='underlying'?textValue(row.underlying_symbol):`${k.toUpperCase()} ${side(row)===k?'· selected':''}`}</th><td>{numeric(row[k==='underlying'?'underlying_entry_open':`${k}_entry_open`])}</td>{['max','min','endpoint'].map(f=><td key={f}><b>{numeric(d[f])}</b><small style={{display:'block'}}>Δ {numeric(d[`${f}_change`],2,true)} · {time(d[`${f}_at`])} IST</small></td>)}</tr>;})}</tbody></table></div>
 <h3>Option P&amp;L · {exit==='max'?'exit at high':exit==='min'?'exit at low':'exit at latest observed close'}</h3>
 <div className={styles.scroll} tabIndex={0} role="region" aria-label="Gross charges and net option PnL"><table><thead><tr><th>Exact contract</th><th>Lot size × lots</th><th>Quantity</th><th>Price Δ</th><th>Gross ₹</th><th>Charges ₹</th><th>Net ₹</th></tr></thead><tbody>{results.map(r=><tr key={r.instrument}><th>{textValue(row[`${r.instrument}_symbol`])}</th><td>{textValue(r.lot)} × {lots||'—'}</td><td>{textValue(r.qty)}</td><td>{numeric(r.pnl?.delta,2,true)}</td><td>{numeric(r.pnl?.gross,2,true)}</td><td>{numeric(r.pnl?.charges)}</td><td><b>{numeric(r.pnl?.net,2,true)}</b></td></tr>)}</tbody></table></div>
 <p>Gross = (exit premium − entry premium) × quantity. CE and PE are independent long-option scenarios, not a combined trade. Underlying change is points, not option Greeks delta. High/low exits are hindsight scenarios, not achievable fills or realised profit.</p>
 <details><summary>Charges, lot source &amp; calculation evidence</summary><p>One buy + one sell, ₹20 brokerage each. NSE premium-based STT, transaction/IPFT, SEBI, GST and buy-side stamp duty use the <a href="https://zerodha.com/brokerage-calculator/#tab-equities" target="_blank" rel="noreferrer">Zerodha F&amp;O Options calculator</a> policy verified 9 Sep 2026. Current-rate estimate, not historical tax reconstruction or a contract note. Excludes slippage, exercise/physical settlement, auto-square-off and income tax. Current exact-contract master lot sizes may not prove historical lot sizes; missing lot size leaves P&amp;L unavailable.</p><p>CE lot as-of {time(row.ce_lot_size_asof)} IST · PE lot as-of {time(row.pe_lot_size_asof)} IST.</p><pre className={styles.raw}>{JSON.stringify(results.map(r=>({instrument:r.instrument,lot:r.lot,...r.pnl})),null,2)}</pre></details>
 </section>;
}
